name: downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: downloader deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cp -r source/asserts/images/textbook/. source/assets/
        cd source/assets/
        ls

        git add -A
        git commit -m "transforming a book into pngs"
        echo "Transform pdf into pics"
        ls -lt
        
        cd ../../
        ls
        git push origin master
