name: Delete documents

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "your email address"
        git config --global user.name "your user name"
        git init
        cd source/asserts/
        git rm -rf html5-css3-3d-cube-puzzle
        git commit -m "remove irrelevant materials"
        git rm -rf videos
        git commit -m "remove files"
        cd ../../
        git push origin master
        

