name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls
        echo '======================='
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=17'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=18'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=19'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=20'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=21'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=22'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=23'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=24'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=25'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=26'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=27'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=28'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=29'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=30'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=31'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=32'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=33'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=34'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=35'
        you-get -o ./you_get/ 'https://www.bilibili.com/video/BV1pg4y1i7T9?p=36'
        
        ls
        echo '------------------------------'
        cd you_get
        ls 
        echo '~~~~~~~~~~~~~~~~~~~~~~'
        cd ../
        cp -r you_get/. Learning-Python-From-Scratch/source/asserts/videos/ImperialCollege/
        cd Learning-Python-From-Scratch/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/asserts/videos/
        git add -A
        git status 
        git commit -m "Add some videos"
        ls
        git push origin master
    
