name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir -p ~/you_get
        ls
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/tensorflow-doc-zh/you_get"
        you-get -o ~/you_get/ -O Diving_into_machine_learning_through_ten 'https://youtu.be/GZBIPwdGtkk?list=PLBkISg6QfSX9HL6us70IBs9slFciFFa4W'
        ls
        echo '------------------------------'
        cd Learning-Python-From-Scratch/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/asserts/videos/
        cp ~/you-get/Diving_into_machine_learning_through_ten.mp4 ./
        git add Diving_into_machine_learning_through_ten.mp4
        git status 
        git commit -m "Add a video"
        ls
        git push origin master
    
