name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls
        echo '======================='
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -x 127.0.0.1:8087 --playlist -o ./you_get/ 'https://www.bilibili.com/video/BV187411f7z9?p=1'
        ls
        echo '------------------------------'
        cd you_get
        ls 
        echo '~~~~~~~~~~~~~~~~~~~~~~'
        cd ../
        cp -r you_get/. Learning-Python-From-Scratch/source/asserts/videos/
        cd Learning-Python-From-Scratch/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd source/asserts/videos/
        git add -A
        git status 
        git commit -m "Add a video"
        ls
        git push origin master
    
