name: tests webbrower

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install setuptools
      run: |
        cd ..
        echo "==============================================================================="
        
        cd Learning-Python-From-Scratch/Project/
        sudo python2 test2.py
